# Generated by Django 5.1.7 on 2025-03-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('direction', models.CharField(choices=[('to_cyrillic', 'Lotin → Kirill'), ('to_latin', 'Kirill → Lotin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
