# Generated by Django 5.1.7 on 2025-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translit_app', '0004_remove_advertisement_image_advertisement_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('sidebar', 'Yon panel'), ('top', 'Tepa'), ('popup', 'Popup')], default='sidebar', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
