# Generated by Django 5.1.7 on 2025-03-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translit_app', '0006_alter_advertisement_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familya/Taxallus')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact_files/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Aloqa yuborilmasi',
                'verbose_name_plural': 'Aloqa yuborilmalari',
            },
        ),
    ]
