# Generated by Django 5.1.7 on 2025-03-09 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translit_app', '0007_contactsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Reklama', 'verbose_name_plural': 'Reklamalar'},
        ),
        migrations.AlterModelOptions(
            name='translationhistory',
            options={'verbose_name': 'Tarjima tarixi', 'verbose_name_plural': 'Tarjima tarixlari'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='ads/', verbose_name='Media fayl'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('sidebar', 'Yon panel'), ('top', 'Tepa'), ('popup', 'Popup'), ('interstitial', 'Interstitial')], default='sidebar', max_length=15, verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='url',
            field=models.URLField(blank=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami +998 bilan boshlanib, 9 ta raqamdan iborat bo‘lishi kerak')], verbose_name='Raqam'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='direction',
            field=models.CharField(max_length=20, verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fayl kengaytmasi'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='original_text',
            field=models.TextField(verbose_name='Asl matn'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='translated_text',
            field=models.TextField(verbose_name='Tarjima qilingan matn'),
        ),
    ]
